### PR TITLE
Fix SPI argument parsing issue

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Close https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3374

TL,DR: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3374#issuecomment-2359002730

Previous PR:
- https://github.com/apple/swift-mmio/pull/104
- https://github.com/apple/swift-mmio/pull/118

### CODE REVIEW

**Comment by finestructure** [comment]
I've deployed a fix in our builder so this shouldn't be necessary. I'll kick off a rebuild of the package to confirm.

**Comment by finestructure** [comment]
Confirmed fixed, this PR is not needed: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3374#issuecomment-2360503818

**Comment by Kyle-Ye** [comment]
> Confirmed fixed, this PR is not needed

Yes. The PR is no longer required. That said. Still think it makes the config more clear that we write each parameter as a separate element.

I'll wait for @rauhul's review opinion for this.

**Comment by rauhul** [comment]
I do prefer these as separate lines as its more clear that it isn't one arg.

**Pull request merged**
