### PR TITLE
Testing Swift CI integration

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@ahoppen is the crash (Swift main) a known macros bug?
```
[315/324] Compiling MMIOTests ExpansionTypeCheckTests.swift
Swift/UnsafeRawPointer.swift:421: Fatal error: load from misaligned raw pointer

*** Signal 4: Backtracing from 0x7f5cdb8d12b4... done ***

*** Program crashed: Illegal instruction at 0x00007f5cdb8d12b4 ***

Thread 0 "MMIOMacros" crashed:

0      0x00007f5cdb8d12b4 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 308 in libswiftCore.so
1 [ra] 0x00007f5cdb8d1062 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 257 in libswiftCore.so
2 [ra] 0x00007f5cdb8d0f1d closure #1 in _assertionFailure(_:_:file:line:flags:) + 380 in libswiftCore.so
3 [ra] 0x00007f5cdb8d0aa6 _assertionFailure(_:_:file:line:flags:) + 229 in libswiftCore.so
4 [ra] 0x00007f5cdb8d0cfe _fatalErrorMessage(_:_:file:line:flags:) + 45 in libswiftCore.so
5 [ra] 0x00007f5cdb9a0190 UnsafeRawBufferPointer.load<A>(fromByteOffset:as:) + 191 in libswiftCore.so
6 [ra] 0x000055a82be5bec2 closure #1 in PluginHostConnection.waitForNextMessage<A>(_:) + 81 in MMIOMacros at /code/.build/checkouts/swift-syntax/Sources/SwiftCompilerPlugin/CompilerPlugin.swift:203:31
7 [ra] 0x00007f5cdaf0f6ca partial apply for closure #1 in Data.InlineData.withUnsafeBytes<A>(_:) + 25 in libFoundation.so
```

**Comment by ahoppen** [comment]
Could you try bumping the version requirement to 509.0.2? This might be https://github.com/apple/swift-syntax/pull/2321, which isn’t in 509.0.1.

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@neonichu @MaxDesiatov if you take a look at https://ci.swift.org/job/pr-swift-mmio-linux-510/8/ you can see the issue I was mentioning a while back where SPM rebuilds my entire library between calls:
```
build: lint
	@echo "building..."
	@swift build \
		--configuration $(CONFIGURATION) \
		--explicit-target-dependency-import-check error

test: build
	@echo "testing..."
	@swift test \
		--configuration $(CONFIGURATION) \
		--parallel \
		--explicit-target-dependency-import-check error
```

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by rauhul** [comment]
Fixes #42

**Pull request merged**
